// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDir42JRzatg11Wb1hkBQ4seM6PDVoGy-Y',
    appId: '1:1094768514893:android:7248ebcb996d7d928c4904',
    messagingSenderId: '1094768514893',
    projectId: 'flutter-course-8f93a',
    storageBucket: 'flutter-course-8f93a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCljwbO14gcguofz0pjdmpYhKYaeU5mXPM',
    appId: '1:1094768514893:ios:8cea004654d90f268c4904',
    messagingSenderId: '1094768514893',
    projectId: 'flutter-course-8f93a',
    storageBucket: 'flutter-course-8f93a.firebasestorage.app',
    androidClientId: '1094768514893-9gcdbvr2lff5ki4gvbee3bv2024ua5mg.apps.googleusercontent.com',
    iosClientId: '1094768514893-3s8qddigpjh2kp8cfo5cihp74a1ho7he.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCourseApp',
  );
}
